# Generated by Django 3.0.7 on 2020-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200708_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='program',
            field=models.TextField(default='Coming Soon'),
        ),
    ]
