# Generated by Django 3.0.7 on 2020-07-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_game_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='program',
            field=models.TextField(default='Paste a program'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('instruction', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Game')),
            ],
        ),
    ]
